apiVersion: v1
kind: Service
metadata:
  name: results-app
  labels:
    name: results-app-service
    app: demo-voting-app
spec:
 type: LoadBalancer
 ports:
  - port: 80
    targetPort: 80
  selectors:
    name: results-app-pod
    app: demo-voting-app

