apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
 type: LoadBalancer
 ports:
  - port: 80
    targetPort: 80
  selectors:
    name: voting-app-pod
    app: demo-voting-app

